### ISSUE TITLE
Adding edge template output preview

### ISSUE THREAD

**Issue by thetutlage** [iconify/documentation#3]
I am not sure if this is the right repo to have this discussion. So please feel free to point me to the correct repo for that.

If I open [this URL](https://icon-sets.iconify.design/heroicons-outline/annotation/). I see a collection of frontend frameworks can one select to copy the code example.
<img width="583" alt="CleanShot 2022-07-12 at 16 42 15@2x" src="https://user-images.githubusercontent.com/1706381/178477153-36ccbee9-3e91-49b3-b856-6d4b30040b87.png">

I am the creator of Node template engine called Edge and have already [created an integration for Iconify](https://github.com/edge-js/edge-iconify) and would love to add the `Edge` in the list of choices as well.

Happy to put in the work to add the option :)

**Comment by cyberalien** [comment]
Sorry for delay. For some reason I wasn't subscribed to this repository, so didn't get notification.

Thanks for creating Edge Iconify! I've added it to website and to documentation.

It will take a while to add it to icon sets website because it uses old spaghetti code that needs refactoring, so adding new options there is currently far from trivial. I'm rewriting whole thing right now, but it will take a while.

**Comment by thetutlage** [comment]
Thanks for adding it to the website. 👍
